### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Akanksha-Sen** [Spyder15/Stock-Calculator#1]
I want to improve the documentation and a bit of html part of website, please assign me.

**Comment by Spyder15** [comment]
Yeah you can work.

**Comment by Akanksha-Sen** [comment]
please assign me this issue to start working upon.

**Comment by Spyder15** [comment]
Can u add some 3 d effect

**Comment by masroor07** [comment]
Can i work on the documentation?

**Comment by Spyder15** [comment]
Yeah u can work

**Comment by masroor07** [comment]
Please assign me with the issue

**Comment by Spyder15** [comment]
> Please assign me with the issue

You can do some 3d effect on front page

**Comment by masroor07** [comment]
Edited the readme file, you might merge the pull request after reviewing the changes
